export const SET_DETAIL_DATA = "SET_DETAIL_DATA";
export const UPDATE_DISCOUNT_MODE = "UPDATE_DISCOUNT_MODE";
export const UPDATE_PRODUCT_PRICE = "UPDATE_PRODUCT_PRICE";
export const UPDATE_PRODUCT_AMOUNT = "UPDATE_PRODUCT_AMOUNT";
export const UPDATE_RELATED_PRODUCTS = "UPDATE_RELATED_PRODUCTS"
export const UPDATE_IS_LOADING_RELATED_PRODUCTS = "UPDATE_IS_LOADING_RELATED_PRODUCTS" 